---
  - name: verify hostname
    fail: msg="provided hostname does not match reported hostname of {{ ansible_nodename }}"
    when: "ansible_nodename not in [ inventory_hostname, inventory_hostname_short ]"
    changed_when: false

  - name: copy Kismatic Inspector to node
    copy:
      src: "{{ kismatic_preflight_checker }}"
      dest: "{{ bin_dir }}/kismatic-inspector"
      mode: 0744

  - name: copy kismatic-inspector.service to remote
    template:
      src: kismatic-inspector.service.j2
      dest: "{{ init_system_dir }}/kismatic-inspector.service"

  - name: reload services
    command: systemctl daemon-reload

  - name: start kismatic-inspector service
    service:
      name: kismatic-inspector.service
      state: started

  # Run the pre-flights checks, and always stop the checker regardless of result
  - block:
      - name: run pre-flight checks using Kismatic Inspector from the master
        command: '{{ bin_dir }}/kismatic-inspector client {{ internal_ipv4 }}:8888 --upgrade -o json --node-roles {{ ",".join(group_names) }}'
        delegate_to: "{{ groups['master'][0] }}"
        register: out
      - name: run pre-flight checks using Kismatic Inspector from the worker
        command: '{{ bin_dir }}/kismatic-inspector client {{ internal_ipv4 }}:8888 --upgrade -o json --node-roles {{ ",".join(group_names) }}'
        delegate_to: "{{ groups['worker'][0] }}"
        register: out
    always:
      - name: stop kismatic-inspector service
        service:
          name: kismatic-inspector.service
          state: stopped
      - name: verify Kismatic Inspector succeeded
        command: /bin/true
        failed_when: "out.rc != 0"