---
  # YUM repo
  - name: ping Kismatic yum repository
    uri: url="{{ yum_gpg_key_url }}"
    notify:
      - add Kismatic yum repository
      - clean Kismatic yum cache # required to get new versions of packagess
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    ignore_errors: yes
    register: result
    until: "result.status is defined and result.status == 200"
    retries: 3
    delay: 1
    changed_when: "result.status is defined and result.status == 200"

  # DEB repo
  - name: ping Kismatic deb repository
    uri: url="{{ deb_gpg_key_url }}"
    notify:
      - install apt-transport-https package
      - add Kismatic deb repository
      - add Kismatic deb key
      - apt-get update
    when: ansible_distribution == 'Ubuntu'
    ignore_errors: yes
    register: result
    until: "result.status is defined and result.status == 200"
    retries: 3
    delay: 1
    changed_when: "result.status is defined and result.status == 200"

  - meta: flush_handlers  #Run handlers

  # install packages
  - name: install etcd package
    package: name=kismatic-etcd{% if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' %}-{{ kismatic_kubernetes_etcd_yum_version }}{% elif ansible_distribution == 'Ubuntu' %}={{ kismatic_kubernetes_etcd_apt_version }}{% endif %} state=present
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes master package
    package: name=kismatic-kubernetes-master{% if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' %}-{{ kismatic_kubernetes_master_yum_version }}{% elif ansible_distribution == 'Ubuntu' %}={{ kismatic_kubernetes_master_apt_version }}{% endif %}  state=present
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes worker package
    package: name=kismatic-kubernetes-node{% if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' %}-{{ kismatic_kubernetes_node_yum_version }}{% elif ansible_distribution == 'Ubuntu' %}={{ kismatic_kubernetes_node_apt_version }}{% endif %}  state=present
    when: "'worker' in group_names and 'master' not in group_names and 'etcd' not in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3
