---
  - name: copy kube-proxy kubeconfig
    template:
      src: kubeconfig.j2
      dest: "{{ kubernetes_kubeconfig.kube_proxy }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"

  - name: copy kube-proxy.yaml manifest
    template:
      src: kube-proxy.yaml
      dest: "{{ kubelet_pod_manifests_dir }}/kube-proxy.yaml"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"

  - include: ../validate-pod/tasks/validate-pod.yaml item="kube-proxy-{{ inventory_hostname|lower }}"
