official_images:
  etcd:
    name: quay.io/coreos/etcd
    version: v3.1.13
  kube_proxy:
    name: gcr.io/google-containers/kube-proxy-amd64
    version: "{{ versions.kubernetes }}"
  kube_controller_manager:
    name: gcr.io/google-containers/kube-controller-manager-amd64
    version: "{{ versions.kubernetes }}"
  kube_scheduler:
    name: gcr.io/google-containers/kube-scheduler-amd64
    version: "{{ versions.kubernetes }}"
  kube_apiserver:
    name: gcr.io/google-containers/kube-apiserver-amd64
    version: "{{ versions.kubernetes }}"
  calico_node:
    name: calico/node
    version: v2.6.9
  calico_ctl:
    name: calico/ctl
    version: v1.6.4
  calico_cni:
    name: calico/cni
    version: v1.11.5
  calico_kube_controller:
    name: calico/kube-controllers
    version: v1.0.4
  cni_bin:
    name: apprenda/cni-bin
    version: v0.6.0
  contiv_netplugin:
    name: contiv/netplugin
    version: 1.1.1
  contiv_authproxy:
    name: contiv/auth_proxy
    version: 1.1.1
  weave:
    name: weaveworks/weave-kube
    version: 2.3.0
  weave_npc:
    name: weaveworks/weave-npc
    version: 2.3.0
  defaultbackend:
    name: gcr.io/google_containers/defaultbackend
    version: 1.4
  nginx_ingress_controller:
    name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    version: 0.12.0
  nginx:
    name: nginx
    version: stable-alpine
  busybox:
    name: busybox
    version: latest
  pause:
    name: gcr.io/google_containers/pause-amd64
    version: 3.0
  kubedns:
    name: gcr.io/google_containers/k8s-dns-kube-dns-amd64
    version: 1.14.9
  kube_dnsmasq:
    name: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64
    version: 1.14.9
  kubedns_sidecar:
    name: gcr.io/google_containers/k8s-dns-sidecar-amd64
    version: 1.14.9
  coredns:
    name: coredns/coredns
    version: 1.1.1
  kubernetes_dashboard:
    name: gcr.io/google_containers/kubernetes-dashboard-amd64
    version: v1.8.3
  apprenda_tcp_healthz: 
    name: apprenda/tcp-healthz-amd64
    version: v1.0.0
  helm:
    name: gcr.io/kubernetes-helm/tiller
    version: v2.8.2
  heapster:
    name: gcr.io/google_containers/heapster-amd64
    version: v1.5.2
  influxdb:
    name: gcr.io/google_containers/heapster-influxdb-amd64
    version: v1.3.3
  rescheduler:
    name: gcr.io/google-containers/rescheduler
    version: v0.3.1
  metrics_server:
    name: gcr.io/google_containers/metrics-server-amd64
    version: v0.2.1