apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-tls
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echoserver-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-tls
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver-tls
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: echoserver-tls
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Ingress
metadata:
  name: echoserver
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kismaticintegration.com
    http:
      paths:
      - path: /echo
        backend:
          serviceName: echoserver
          servicePort: 80
---
apiVersion: apps/v1
kind: Ingress
metadata:
  name: echoserver-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - kismaticintegration.com
    secretName: kismaticintegration-tls
  rules:
  - host: kismaticintegration.com
    http:
      paths:
      - path: /echo-tls
        backend:
          serviceName: echoserver-tls
          servicePort: 80
