apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-proxy
    version: "{{ kubernetes_version }}"
    kismaticVersion: "{{ kismatic_short_version }}"
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: {{ kube_proxy_img }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-proxy
      - --cluster-cidr={{ kubernetes_pods_cidr }}
      - --hostname-override={{ inventory_hostname }}
      - --kubeconfig={{ kubernetes_kubeconfig_path }}
      - --master={{ kubernetes_master_ip }}
      - --proxy-mode=iptables
      - --v=2
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: "{{ kubernetes_kubeconfig_path }}"
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes
        name: "etc-kube-ssl"
        readOnly: true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10249
      initialDelaySeconds: 15
      timeoutSeconds: 5
  volumes:
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "{{ kubernetes_kubeconfig_path }}"
    - name: "etc-kube-ssl"
      hostPath:
        path: "/etc/kubernetes"
