apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-proxy
    kismatic/host: {{ inventory_hostname }}
  annotations:
    version: "{{ official_images.kube_apiserver.version }}"
    kismatic/version: "{{ kismatic_short_version }}"
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: {{ images.kube_proxy }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-proxy
{% set combined_options = kube_proxy_option_defaults | combine(kube_proxy_option_overrides) -%}
{% for option in combined_options | dictsort %}
{% if option[1] is defined and option[1] | string | length > 0 %}
      - --{{ option[0] }}={{ option[1] }}
{% endif %}
{% endfor %}
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: "{{ kubernetes_kubeconfig.kube_proxy }}"
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes
        name: "etc-kube-ssl"
        readOnly: true
      - mountPath: /lib/modules
        name: "lib-modules"
        readOnly: true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10256
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
  volumes:
    - name: "lib-modules"
      hostPath:
        path: "/lib/modules"
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "{{ kubernetes_kubeconfig.kube_proxy }}"
    - name: "etc-kube-ssl"
      hostPath:
        path: "/etc/kubernetes"
