apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-apiserver
    kismatic/host: {{ inventory_hostname }}
  annotations:
    version: "{{ kubernetes_version }}"
    kismatic/version: "{{ kismatic_short_version }}"
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: {{ kube_apiserver_img }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-apiserver
{% set combined_options = kubernetes_api_server_option_defaults | combine(kubernetes_api_server_option_overrides) -%}
{% for option in combined_options | dictsort %}
{% if option[1] is defined and option[1] | string | length > 0 %}
      - --{{ option[0] }}={{ option[1] }}
{% endif %}
{% endfor %}
    ports:
    - containerPort: {{ kubernetes_master_secure_port }}
      hostPort: {{ kubernetes_master_secure_port }}
      name: https
    - containerPort: {{ kubernetes_master_insecure_port }}
      hostPort: {{ kubernetes_master_insecure_port }}
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - name: usr-ca-certs-host
      mountPath: /usr/share/ca-certificates
      readOnly: true
{% if cloud_provider is defined and cloud_provider == 'aws' and ansible_os_family == 'RedHat' %}
    - mountPath: /etc/ssl/certs/ca-bundle.crt
      name: rhel-ca-bundle
      readOnly: true
{% endif %}
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: {{ kubernetes_master_insecure_port }}
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: ssl-certs-kubernetes
  - hostPath:
      path: /etc/ssl/certs/
    name: ssl-certs-host
  - hostPath:
      path: /usr/share/ca-certificates
    name: usr-ca-certs-host
{% if cloud_provider is defined and cloud_provider == 'aws' and ansible_os_family == 'RedHat' %}
  - hostPath:
      path: /etc/ssl/certs/ca-bundle.crt
    name: rhel-ca-bundle
{% endif %}