---
  - name: create {{ network_plugin_dir }} directory
    file:
      path: "{{ network_plugin_dir }}"
      state: directory
      
  - name: create /etc/weave directory
    file:
      path: "{{ weave_dir }}"
      state: directory

  - name: copy weavenet.conflist to remote
    template:
        src: weavenet.conflist
        dest: "{{ network_plugin_dir }}/00-weave.conflist"
        owner: "{{ kubernetes_owner }}"
        group: "{{ kubernetes_group }}"
        mode: "{{ kubernetes_service_mode }}"

  - name: copy weave.yaml to remote
    template:
      src: weave.yaml
      dest: "{{weave_dir}}/weave.yaml"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"

  - name: get the name of the weave pod running on this node
    command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} get pods -l=k8s-app=weave-net --template {%raw%}'{{range .items}}{{if eq .spec.nodeName{%endraw%} "{{ inventory_hostname|lower }}"{%raw%}}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}'{%endraw%} -n kube-system
    register: pod_name
    when: upgrading is defined and upgrading|bool == true

  - name: start weave containers
    command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} apply -f /etc/weave/weave.yaml
    run_once: true

  - name: delete weave pod running on this node
    command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} delete pod {{ pod_name.stdout }} -n kube-system --now --ignore-not-found=true
    when: pod_name is defined and pod_name.stdout is defined and pod_name.stdout != ""
