---
  # YUM
  - name: install kubelet yum package
    yum:
      name: kubelet-{{ kubernetes_yum_version }}
      state: present
      disablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}*{% endif %}'
      enablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}kismatic-*{% endif %}'
    register: kubelet_installation_rpm
    until: kubelet_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"

  - name: install kubectl yum package
    yum:
      name: kubectl-{{ kubernetes_yum_version }}
      state: present
      disablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}*{% endif %}'
      enablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}kismatic-*{% endif %}'
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"

  # DEB
  - name: install kubelet deb package
    apt:
      name: kubelet={{ kubernetes_deb_version }}
      state: present
      allow_unauthenticated: '{% if package_repository_urls is defined and package_repository_urls != "" %}yes{% else %}no{% endif %}'
      default_release: kubernetes-xenial
    register: kubelet_installation_deb
    until: kubelet_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: install kubectl deb package
    apt:
      name: kubectl={{ kubernetes_deb_version }}
      state: present
      allow_unauthenticated: '{% if package_repository_urls is defined and package_repository_urls != "" %}yes{% else %}no{% endif %}'
      default_release: kubernetes-xenial
    register: result
    until: result|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"