---
  - hosts: all
    any_errors_fatal: true
    name: "{{ play_name | default('Copy Addition Files and Directories') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    roles:
      - role: additional-files
