---
  - hosts: master[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Start Calico Network Policy') }}"
    become: yes
    run_once: true
    vars_files:
      - group_vars/all.yaml
      - group_vars/container_images.yaml

    pre_tasks:
      - name: remove old calico-policy-controller replication controller if exists
        command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} delete rc calico-policy-controller -n kube-system --now --ignore-not-found
        when: upgrading is defined and upgrading|bool == true
      - name: remove old calico-policy-controller deployment if exists
        command: kubectl --kubeconfig {{ kubernetes_kubeconfig.kubectl }} delete deployment calico-policy-controller -n kube-system --now --ignore-not-found
        when: upgrading is defined and upgrading|bool == true

    roles:
      - calico-network-policy