---
  - hosts: master[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Configure Calico Network Policy') }}"
    remote_user: root
    become: yes
    run_once: true

    pre_tasks:
      - name: remove old calico-policy-controller replication controller if exists
        command: kubectl delete rc calico-policy-controller -n kube-system --now --ignore-not-found
        when: upgrading is defined and upgrading|bool == true

    roles:
      - calico-network-policy