---
  - hosts: all
    any_errors_fatal: true
    name: "{{ play_name | default('Install Docker') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    roles:
      - role: packages-docker
        when: allow_package_installation|bool == true
      - role: docker-storage
      - role: docker-proxy
        when: >
          (https_proxy is defined and https_proxy != "") or
          (http_proxy is defined and http_proxy != "") or
          (no_proxy is defined and no_proxy != "")
      - role: docker
