---
  - hosts: etcd
    any_errors_fatal: true
    name: "{{ play_name | default('Start Network Etcd Cluster') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-networking.yaml

    pre_tasks:
      - name: download etcd image
        command: docker pull {{ etcd_img }}

    roles:
      - role: etcd-backup
        when: upgrading is defined and upgrading|bool == true
      - role: etcd
