---
  - hosts: etcd
    any_errors_fatal: true
    name: "Temporarily Install Transition Etcd 3.x version"
    serial: 1 # need to always do this serially
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-networking.yaml
      
    roles:
      - role: etcd-version
      - role: packages-transition-etcd  # don' install packages if etcd version is not changing
        when: >
          (allow_package_installation|bool == true) and
          (etcd_needs_upgrade is defined and etcd_needs_upgrade|bool == true)
      - role: etcd-backup
      - role: etcd
        etcd_install_bin_name: etcd_v3_0
        etcdctl_install_bin_name: etcdctl_v3_0
