---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Controller Manager') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: download kube-controller-manager image
        command: docker pull {{ kube_controller_manager_img }}

      - name: check if kube-controller-manager service is active
        command: systemctl is-active -q kube-controller-manager.service
        register: status
        failed_when: status.rc !=0 and status.rc != 3 # 0 = running, 3 = stopped/doesn't exist
        when: upgrading is defined and upgrading|bool == true

      - name: stop kube-controller-manager service if running
        service:
          name: kube-controller-manager.service
          state: stopped
          enabled: no
        when: upgrading is defined and upgrading|bool == true and status is defined and status.rc == 0
      - name: remove unnecessary kube-controller-manager unit file
        file:
          path: "{{ init_system_dir }}/kube-controller-manager.service"
          state: absent
        when: upgrading is defined and upgrading|bool == true

    roles:
      - kube-controller-manager
