---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes API Server') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: download kube-apiserver image
        command: docker pull {{ kube_apiserver_img }}

      - name: check if kube-apiserver service is active
        command: systemctl is-active -q kube-apiserver.service
        register: status
        failed_when: status.rc !=0 and status.rc != 3 # 0 = running. 3 = stopped/doesn't exist
        when: upgrading is defined and upgrading|bool == true

      - name: stop kube-apiserver service
        service:
          name: kube-apiserver.service
          state: stopped
          enabled: no
        when: upgrading is defined and upgrading|bool == true and status is defined and status.rc == 0 # only stop if it's running
      - name: remove unnecessary kube-apiserver unit file
        file:
          path: "{{ init_system_dir }}/kube-apiserver.service"
          state: absent
        when: upgrading is defined and upgrading|bool == true and status is defined and status.rc == 0

    roles:
      - authorization-policy
      - kube-apiserver
