---
  - hosts: master:!worker
    any_errors_fatal: true
    name: "Install Kubernetes Kubelet on Master Nodes"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    vars:
      - kubernetes_schedulable: false

    roles:
      - kubeconfig
      - kubelet
