---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Proxy') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: download kube-proxy image
        command: docker pull {{ kube_proxy_img }}

      - name: check if kube-proxy service is active
        command: systemctl is-active -q kube-proxy.service
        register: status
        failed_when: status.rc != 0 and status.rc != 3 # 0 = running, 3 = stopped/doesn't exist
        when: upgrading is defined and upgrading|bool == true

      - name: stop kube-proxy service
        service:
          name: kube-proxy.service
          state: stopped
          enabled: no
        when: upgrading is defined and upgrading|bool == true and status is defined and status.rc == 0 
      - name: remove unnecessary kube-proxy unit file
        file:
          path: "{{ init_system_dir }}/kube-proxy.service"
          state: absent
        when: upgrading is defined and upgrading|bool == true and status is defined and status.rc == 0 

    roles:
      - kube-proxy
