---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: Label Kubernetes Nodes 
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml
      
    tasks:
      - name: label nodes with system labels
        command: kubectl label --overwrite nodes --selector kubernetes.io/hostname={{ inventory_hostname }} --kubeconfig {{ kubernetes_kubeconfig_path }} kismatic/cni-provider={{ cni.provider| quote }}{% if 'ingress' in group_names%} kismatic/ingress=true{% endif %}{% if 'storage' in group_names%} kismatic/storage=true{% endif %}
        
      - name: label nodes with user defined labels
        command: kubectl label --overwrite nodes --selector kismatic/host={{ inventory_hostname }} --kubeconfig {{ kubernetes_kubeconfig_path }} {{ node_labels[inventory_hostname] | join(" ") }}
        when: node_labels[inventory_hostname] is defined and node_labels[inventory_hostname]|length > 0