---
  - include: _all.yaml
  - include: _hosts.yaml
    when: modify_hosts_file|bool == true
  - include: _certs.yaml
  - include: _kubeconfig.yaml
  - include: _packages-repo.yaml
    when: allow_package_installation|bool == true
  - include: _docker.yaml
  - include: _kubelet.yaml
  - include: _kube-proxy.yaml
  - include: _label-nodes.yaml
  - include: _cni.yaml
    when: cni.enabled|bool == true
  - include: _calico.yaml
    when: cni.enabled|bool == true and cni.provider == "calico"
  - include: _calico-validate.yaml
    when: cni.enabled|bool == true and cni.provider == "calico"
  - include: _weave.yaml
    when: cni.enabled|bool == true and cni.provider == "weave"
  - include: _weave-validate.yaml
    when: cni.enabled|bool == true and cni.provider == "weave"
  - include: _contiv.yaml
    when: cni.enabled|bool == true and cni.provider == "contiv"
  - include: _update-version.yaml
