---
  - include: _packages.yaml
    when: allow_package_installation|bool == true
  
  # docker
  - include: _docker.yaml play_name="Upgrade Docker" serial="1"

  # etcd
  #- include: _etcd-k8s.yaml play_name="Upgrade Kubernetes Etcd Cluster" serial="1"
  #- include: _etcd-networking.yaml play_name="Upgrade Network Etcd Cluster" serial="1"

  # kubernetes
  - include: _kubelet.yaml play_name="Upgrade Kubernetes Kubelet" serial="1"
  - include: _kube-apiserver.yaml play_name="Upgrade Kubernetes API Server" serial="1" upgrading=true
  - include: _kube-scheduler.yaml play_name="Upgrade Kubernetes Scheduler" serial="1" upgrading=true
  - include: _kube-controller-manager.yaml play_name="Upgrade Kubernetes Controller Manager" serial="1" upgrading=true
  - include: _kube-proxy.yaml play_name="Upgrade Kubernetes Proxy" serial="1" upgrading=true
  - include: _calico.yaml play_name="Upgrade Cluster Network" serial="1" upgrading=true

  - include: _upgrade-cleanup.yaml
  - include: _update-version.yaml
