apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-controller-manager
  annotations:
    version: "{{ kubernetes_version }}"
    kismatic/version: "{{ kismatic_short_version }}"
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: {{ kube_controller_manager_img }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-controller-manager
      - --allocate-node-cidrs=true
      - --cluster-cidr={{ kubernetes_pods_cidr }}
      - --cluster-name={{ kubernetes_cluster_name }}
      - --kubeconfig={{ kubernetes_kubeconfig.controller_manager }}
      - --leader-elect=true
      - --root-ca-file={{ kubernetes_certificates.ca }}
      - --service-account-private-key-file={{ kubernetes_certificates.service_account_key }}
      - --service-cluster-ip-range={{ kubernetes_services_cidr }}
      - --use-service-account-credentials=true
      - --v=2
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
    volumeMounts:
    - mountPath: "{{ kubernetes_kubeconfig.controller_manager }}"
      name: "kubeconfig"
      readOnly: true
    - mountPath: /etc/kubernetes
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - name: "kubeconfig"
    hostPath:
      path: "{{ kubernetes_kubeconfig.controller_manager }}"
  - hostPath:
      path: /etc/kubernetes
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
