apiVersion: v1
kind: Pod
metadata:
  name: rescheduler
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    k8s-app: rescheduler
    version: {{ official_images.rescheduler.version }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Rescheduler"
spec:
  hostNetwork: true
  containers:
  - image: {{ images.rescheduler }}
    name: rescheduler
    volumeMounts:
    # TODO: Make resource requirements depend on the size of the cluster
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    command:
    command:
    - /rescheduler 
    - --running-in-cluster=false
    volumeMounts:
      - mountPath: "/root/.kube/config"
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes
        name: ssl-certs-kubernetes
        readOnly: true
  volumes:
    - name: "kubeconfig"
      hostPath:
        path: "{{ kubernetes_kubeconfig.rescheduler }}"
    - hostPath:
        path: /etc/kubernetes
      name: ssl-certs-kubernetes