---
  - name: get storage cluster IP
    command: kubectl get svc kismatic-storage -n kube-system -o=jsonpath='{.spec.clusterIP}'
    register: out

  - name: set storage cluster IP
    set_fact:
      storage_cluster_ip: "{{ out.stdout }}"

  - name: copy pv.yaml to remote
    template:
        src: pv.yaml
        dest: /tmp/pv.yaml

  - name: create persistent volume {{ volume_name }}
    command: kubectl apply -f /tmp/pv.yaml
