---
  # YUM
  - name: ping Kismatic yum repository
    uri: url="{{ yum_gpg_key_url }}"
    when: ansible_os_family == 'RedHat'
    ignore_errors: yes
    register: kismatic_result
    until: "kismatic_result.status is defined and kismatic_result.status == 200"
    retries: 3
    delay: 1
    changed_when: "kismatic_result.status is defined and kismatic_result.status == 200"
  - name: add Kismatic yum repository
    yum_repository:
      name: kismatic
      description: Kismatic Packages
      baseurl: "{{ yum_repository_url }}"
      gpgkey: "{{ yum_gpg_key_url }}"
      gpgcheck: yes
    when: ansible_os_family == 'RedHat' and kismatic_result.status is defined and kismatic_result.status == 200
  - name: clean kismatic yum cache
    command: 'yum --enablerepo=kismatic clean metadata'
    when: ansible_os_family == 'RedHat' and kismatic_result.status is defined and kismatic_result.status == 200

  # DEB
  - name: ping Kismatic deb repository
    uri: url="{{ deb_gpg_key_url }}"
    when: ansible_os_family == 'Debian'
    ignore_errors: yes
    register: kismatic_result
    until: "kismatic_result.status is defined and kismatic_result.status == 200"
    retries: 3
    delay: 1
    changed_when: "kismatic_result.status is defined and kismatic_result.status == 200"

  - name: install apt-transport-https package
    apt:
      name: apt-transport-https
      state: latest
      update_cache: yes
    when: ansible_os_family == 'Debian' and kismatic_result.status is defined and kismatic_result.status == 200
  - name: add Kismatic deb key
    apt_key:
      url: "{{ deb_gpg_key_url }}"
      validate_certs: no
    when: ansible_os_family == 'Debian' and kismatic_result.status is defined and kismatic_result.status == 200
  - name: add Kismatic deb repository
    apt_repository:
      repo: 'deb {{ deb_repository_url }} kismatic-xenial main'
      validate_certs: no
    when: ansible_os_family == 'Debian' and kismatic_result.status is defined and kismatic_result.status == 200
  - name: apt-get update
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian' and kismatic_result.status is defined and kismatic_result.status == 200
