---
  # YUM
  - name: add Kismatic yum repository
    yum_repository:
      name: kismatic
      description: Kismatic Packages
      baseurl: "{{ yum_repository_url }}"
      gpgkey: "{{ yum_gpg_key_url }}"
      gpgcheck: yes
    when: ansible_os_family == 'RedHat'

  - name: add Gluster yum repository
    yum_repository:
      name: gluster
      description: Gluster 3.8
      baseurl: "http://buildlogs.centos.org/centos/7/storage/x86_64/gluster-3.8/"
      gpgkey: "https://download.gluster.org/pub/gluster/glusterfs/3.8/3.8.7/rsa.pub"
      gpgcheck: yes
    when: ansible_os_family == 'RedHat' and 'storage' in group_names

  - name: clean kismatic yum cache
    command: 'yum --disablerepo="*" --enablerepo="kismatic,gluster" makecache'
    when: ansible_os_family == 'RedHat'

  # DEB
  - name: install apt-transport-https package
    apt:
      name: apt-transport-https
      state: latest
      update_cache: yes
    when: ansible_os_family == 'Debian'

  - name: add Kismatic deb key
    apt_key:
      url: "{{ deb_gpg_key_url }}"
      validate_certs: no
    when: ansible_os_family == 'Debian'

  - name: add Kismatic deb repository
    apt_repository:
      repo: 'deb {{ deb_repository_url }} kismatic-xenial main'
      validate_certs: no
    when: ansible_os_family == 'Debian'
  - name: add Gluster deb repository
    apt_repository:
      repo: ppa:gluster/glusterfs-3.8
      update_cache: yes
    when: ansible_os_family == 'Debian' and 'storage' in group_names

  - name: apt-get update
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'
